# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\gergely.padanyi\.qgis\python\plugins\LelohelyBejelento\ui_lelohelybejelento.ui'
#
# Created: Tue Apr 09 11:27:30 2013
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_LelohelyBejelento(object):
    def setupUi(self, LelohelyBejelento):
        LelohelyBejelento.setObjectName(_fromUtf8("LelohelyBejelento"))
        LelohelyBejelento.resize(491, 661)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LelohelyBejelento.sizePolicy().hasHeightForWidth())
        LelohelyBejelento.setSizePolicy(sizePolicy)
        LelohelyBejelento.setMinimumSize(QtCore.QSize(491, 661))
        LelohelyBejelento.setMaximumSize(QtCore.QSize(491, 661))
        self.buttonBox = QtGui.QDialogButtonBox(LelohelyBejelento)
        self.buttonBox.setGeometry(QtCore.QRect(320, 630, 161, 23))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.tabWidget = QtGui.QTabWidget(LelohelyBejelento)
        self.tabWidget.setGeometry(QtCore.QRect(10, 40, 471, 581))
        self.tabWidget.setCursor(QtCore.Qt.ArrowCursor)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.Section01 = QtGui.QGroupBox(self.tab1)
        self.Section01.setGeometry(QtCore.QRect(10, 10, 441, 171))
        self.Section01.setObjectName(_fromUtf8("Section01"))
        self.CountyName = QtGui.QLabel(self.Section01)
        self.CountyName.setGeometry(QtCore.QRect(30, 20, 71, 16))
        self.CountyName.setObjectName(_fromUtf8("CountyName"))
        self.CityName = QtGui.QLabel(self.Section01)
        self.CityName.setGeometry(QtCore.QRect(30, 50, 91, 16))
        self.CityName.setObjectName(_fromUtf8("CityName"))
        self.Hazszam = QtGui.QLineEdit(self.Section01)
        self.Hazszam.setGeometry(QtCore.QRect(120, 110, 311, 20))
        self.Hazszam.setObjectName(_fromUtf8("Hazszam"))
        self.HouseName = QtGui.QLabel(self.Section01)
        self.HouseName.setGeometry(QtCore.QRect(30, 110, 51, 16))
        self.HouseName.setObjectName(_fromUtf8("HouseName"))
        self.KOHAzon = QtGui.QLineEdit(self.Section01)
        self.KOHAzon.setGeometry(QtCore.QRect(180, 140, 251, 20))
        self.KOHAzon.setInputMethodHints(QtCore.Qt.ImhNone)
        self.KOHAzon.setObjectName(_fromUtf8("KOHAzon"))
        self.KOHName = QtGui.QLabel(self.Section01)
        self.KOHName.setGeometry(QtCore.QRect(30, 140, 151, 16))
        self.KOHName.setObjectName(_fromUtf8("KOHName"))
        self.Utca = QtGui.QLineEdit(self.Section01)
        self.Utca.setGeometry(QtCore.QRect(120, 80, 311, 20))
        self.Utca.setText(_fromUtf8(""))
        self.Utca.setObjectName(_fromUtf8("Utca"))
        self.RoadName = QtGui.QLabel(self.Section01)
        self.RoadName.setGeometry(QtCore.QRect(30, 80, 71, 16))
        self.RoadName.setObjectName(_fromUtf8("RoadName"))
        self.Megye = QtGui.QComboBox(self.Section01)
        self.Megye.setGeometry(QtCore.QRect(140, 20, 291, 22))
        self.Megye.setObjectName(_fromUtf8("Megye"))
        self.Telepules = QtGui.QComboBox(self.Section01)
        self.Telepules.setGeometry(QtCore.QRect(140, 50, 291, 22))
        self.Telepules.setObjectName(_fromUtf8("Telepules"))
        self.chckMegye = QtGui.QCheckBox(self.Section01)
        self.chckMegye.setGeometry(QtCore.QRect(120, 20, 16, 17))
        self.chckMegye.setText(_fromUtf8(""))
        self.chckMegye.setObjectName(_fromUtf8("chckMegye"))
        self.chckTelepules = QtGui.QCheckBox(self.Section01)
        self.chckTelepules.setGeometry(QtCore.QRect(120, 50, 16, 17))
        self.chckTelepules.setText(_fromUtf8(""))
        self.chckTelepules.setObjectName(_fromUtf8("chckTelepules"))
        self.Section02 = QtGui.QGroupBox(self.tab1)
        self.Section02.setGeometry(QtCore.QRect(10, 190, 441, 51))
        self.Section02.setObjectName(_fromUtf8("Section02"))
        self.LeloNev = QtGui.QLineEdit(self.Section02)
        self.LeloNev.setGeometry(QtCore.QRect(20, 20, 411, 20))
        self.LeloNev.setObjectName(_fromUtf8("LeloNev"))
        self.Section03 = QtGui.QGroupBox(self.tab1)
        self.Section03.setGeometry(QtCore.QRect(10, 250, 441, 291))
        self.Section03.setObjectName(_fromUtf8("Section03"))
        self.CRSName = QtGui.QLabel(self.Section03)
        self.CRSName.setGeometry(QtCore.QRect(20, 20, 171, 16))
        self.CRSName.setObjectName(_fromUtf8("CRSName"))
        self.CRSAzon = QtGui.QLineEdit(self.Section03)
        self.CRSAzon.setGeometry(QtCore.QRect(190, 20, 241, 20))
        self.CRSAzon.setText(_fromUtf8(""))
        self.CRSAzon.setObjectName(_fromUtf8("CRSAzon"))
        self.MapNumberName = QtGui.QLabel(self.Section03)
        self.MapNumberName.setGeometry(QtCore.QRect(20, 50, 91, 16))
        self.MapNumberName.setObjectName(_fromUtf8("MapNumberName"))
        self.EOVSzelveny = QtGui.QLineEdit(self.Section03)
        self.EOVSzelveny.setGeometry(QtCore.QRect(190, 50, 241, 20))
        self.EOVSzelveny.setObjectName(_fromUtf8("EOVSzelveny"))
        self.HRSZ = QtGui.QLineEdit(self.Section03)
        self.HRSZ.setGeometry(QtCore.QRect(190, 80, 241, 20))
        self.HRSZ.setObjectName(_fromUtf8("HRSZ"))
        self.FoldrLeiras = QtGui.QPlainTextEdit(self.Section03)
        self.FoldrLeiras.setGeometry(QtCore.QRect(30, 130, 401, 121))
        self.FoldrLeiras.setObjectName(_fromUtf8("FoldrLeiras"))
        self.Pontossag = QtGui.QLineEdit(self.Section03)
        self.Pontossag.setGeometry(QtCore.QRect(220, 260, 211, 20))
        self.Pontossag.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.Pontossag.setObjectName(_fromUtf8("Pontossag"))
        self.HRSZName = QtGui.QLabel(self.Section03)
        self.HRSZName.setGeometry(QtCore.QRect(20, 80, 91, 16))
        self.HRSZName.setObjectName(_fromUtf8("HRSZName"))
        self.GeoDescriptionName = QtGui.QLabel(self.Section03)
        self.GeoDescriptionName.setGeometry(QtCore.QRect(20, 110, 71, 16))
        self.GeoDescriptionName.setObjectName(_fromUtf8("GeoDescriptionName"))
        self.AccuracyName = QtGui.QLabel(self.Section03)
        self.AccuracyName.setGeometry(QtCore.QRect(20, 260, 181, 16))
        self.AccuracyName.setObjectName(_fromUtf8("AccuracyName"))
        self.chckPontossag = QtGui.QCheckBox(self.Section03)
        self.chckPontossag.setGeometry(QtCore.QRect(200, 260, 16, 17))
        self.chckPontossag.setText(_fromUtf8(""))
        self.chckPontossag.setObjectName(_fromUtf8("chckPontossag"))
        self.tabWidget.addTab(self.tab1, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.Section04 = QtGui.QGroupBox(self.tab2)
        self.Section04.setEnabled(True)
        self.Section04.setGeometry(QtCore.QRect(10, 10, 441, 531))
        self.Section04.setObjectName(_fromUtf8("Section04"))
        self.AddJellegKorButton = QtGui.QPushButton(self.Section04)
        self.AddJellegKorButton.setGeometry(QtCore.QRect(330, 80, 101, 23))
        self.AddJellegKorButton.setObjectName(_fromUtf8("AddJellegKorButton"))
        self.RemoveJellegKorButton = QtGui.QPushButton(self.Section04)
        self.RemoveJellegKorButton.setGeometry(QtCore.QRect(330, 110, 101, 23))
        self.RemoveJellegKorButton.setObjectName(_fromUtf8("RemoveJellegKorButton"))
        self.KorCombo = QtGui.QComboBox(self.Section04)
        self.KorCombo.setGeometry(QtCore.QRect(230, 20, 201, 22))
        self.KorCombo.setMaxVisibleItems(30)
        self.KorCombo.setMaxCount(2147483647)
        self.KorCombo.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.KorCombo.setObjectName(_fromUtf8("KorCombo"))
        self.JellegCombo = QtGui.QComboBox(self.Section04)
        self.JellegCombo.setGeometry(QtCore.QRect(10, 20, 211, 22))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.JellegCombo.sizePolicy().hasHeightForWidth())
        self.JellegCombo.setSizePolicy(sizePolicy)
        self.JellegCombo.setMaxVisibleItems(30)
        self.JellegCombo.setObjectName(_fromUtf8("JellegCombo"))
        self.PontosKor = QtGui.QLineEdit(self.Section04)
        self.PontosKor.setGeometry(QtCore.QRect(252, 50, 181, 20))
        self.PontosKor.setObjectName(_fromUtf8("PontosKor"))
        self.PontosJelleg = QtGui.QLineEdit(self.Section04)
        self.PontosJelleg.setGeometry(QtCore.QRect(30, 50, 191, 20))
        self.PontosJelleg.setObjectName(_fromUtf8("PontosJelleg"))
        self.JellegKorTable = QtGui.QTableWidget(self.Section04)
        self.JellegKorTable.setGeometry(QtCore.QRect(10, 80, 311, 441))
        self.JellegKorTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.JellegKorTable.setAlternatingRowColors(True)
        self.JellegKorTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.JellegKorTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.JellegKorTable.setObjectName(_fromUtf8("JellegKorTable"))
        self.JellegKorTable.setColumnCount(2)
        self.JellegKorTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.JellegKorTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.JellegKorTable.setHorizontalHeaderItem(1, item)
        self.JellegKorTable.horizontalHeader().setVisible(False)
        self.JellegKorTable.horizontalHeader().setDefaultSectionSize(150)
        self.tabWidget.addTab(self.tab2, _fromUtf8(""))
        self.tab3 = QtGui.QWidget()
        self.tab3.setObjectName(_fromUtf8("tab3"))
        self.Section05 = QtGui.QGroupBox(self.tab3)
        self.Section05.setGeometry(QtCore.QRect(10, 10, 441, 51))
        self.Section05.setObjectName(_fromUtf8("Section05"))
        self.LelohelyAllapot = QtGui.QComboBox(self.Section05)
        self.LelohelyAllapot.setGeometry(QtCore.QRect(20, 20, 231, 22))
        self.LelohelyAllapot.setObjectName(_fromUtf8("LelohelyAllapot"))
        self.EgyebAllapot = QtGui.QLineEdit(self.Section05)
        self.EgyebAllapot.setGeometry(QtCore.QRect(260, 20, 171, 20))
        self.EgyebAllapot.setObjectName(_fromUtf8("EgyebAllapot"))
        self.Section06 = QtGui.QGroupBox(self.tab3)
        self.Section06.setGeometry(QtCore.QRect(10, 70, 441, 51))
        self.Section06.setObjectName(_fromUtf8("Section06"))
        self.LelohelyVeszely = QtGui.QComboBox(self.Section06)
        self.LelohelyVeszely.setGeometry(QtCore.QRect(20, 20, 231, 22))
        self.LelohelyVeszely.setObjectName(_fromUtf8("LelohelyVeszely"))
        self.EgyebVeszely = QtGui.QLineEdit(self.Section06)
        self.EgyebVeszely.setGeometry(QtCore.QRect(260, 20, 171, 20))
        self.EgyebVeszely.setObjectName(_fromUtf8("EgyebVeszely"))
        self.Section07 = QtGui.QGroupBox(self.tab3)
        self.Section07.setGeometry(QtCore.QRect(10, 130, 441, 161))
        self.Section07.setObjectName(_fromUtf8("Section07"))
        self.ForrasTipusValue = QtGui.QComboBox(self.Section07)
        self.ForrasTipusValue.setGeometry(QtCore.QRect(136, 20, 111, 22))
        self.ForrasTipusValue.setObjectName(_fromUtf8("ForrasTipusValue"))
        self.ForrasTable = QtGui.QTableWidget(self.Section07)
        self.ForrasTable.setGeometry(QtCore.QRect(16, 50, 411, 101))
        self.ForrasTable.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.ForrasTable.setAlternatingRowColors(True)
        self.ForrasTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.ForrasTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.ForrasTable.setObjectName(_fromUtf8("ForrasTable"))
        self.ForrasTable.setColumnCount(4)
        self.ForrasTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.ForrasTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.ForrasTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.ForrasTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.ForrasTable.setHorizontalHeaderItem(3, item)
        self.ForrasTable.horizontalHeader().setDefaultSectionSize(100)
        self.AddForrasButton = QtGui.QPushButton(self.Section07)
        self.AddForrasButton.setGeometry(QtCore.QRect(256, 20, 101, 23))
        self.AddForrasButton.setObjectName(_fromUtf8("AddForrasButton"))
        self.RemoveForrasButton = QtGui.QPushButton(self.Section07)
        self.RemoveForrasButton.setGeometry(QtCore.QRect(360, 20, 61, 23))
        self.RemoveForrasButton.setObjectName(_fromUtf8("RemoveForrasButton"))
        self.Ismertseg = QtGui.QComboBox(self.Section07)
        self.Ismertseg.setGeometry(QtCore.QRect(16, 20, 111, 22))
        self.Ismertseg.setObjectName(_fromUtf8("Ismertseg"))
        self.Section08 = QtGui.QGroupBox(self.tab3)
        self.Section08.setGeometry(QtCore.QRect(10, 300, 441, 251))
        self.Section08.setObjectName(_fromUtf8("Section08"))
        self.TevekenysegTable = QtGui.QTableWidget(self.Section08)
        self.TevekenysegTable.setGeometry(QtCore.QRect(20, 50, 411, 191))
        self.TevekenysegTable.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.TevekenysegTable.setAlternatingRowColors(True)
        self.TevekenysegTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.TevekenysegTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.TevekenysegTable.setObjectName(_fromUtf8("TevekenysegTable"))
        self.TevekenysegTable.setColumnCount(4)
        self.TevekenysegTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.TevekenysegTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.TevekenysegTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.TevekenysegTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.TevekenysegTable.setHorizontalHeaderItem(3, item)
        self.TevekenysegTable.horizontalHeader().setDefaultSectionSize(100)
        self.AddTevekenysegButton = QtGui.QPushButton(self.Section08)
        self.AddTevekenysegButton.setGeometry(QtCore.QRect(230, 20, 111, 23))
        self.AddTevekenysegButton.setObjectName(_fromUtf8("AddTevekenysegButton"))
        self.RemoveTevekenysegButton = QtGui.QPushButton(self.Section08)
        self.RemoveTevekenysegButton.setGeometry(QtCore.QRect(350, 20, 75, 23))
        self.RemoveTevekenysegButton.setObjectName(_fromUtf8("RemoveTevekenysegButton"))
        self.tabWidget.addTab(self.tab3, _fromUtf8(""))
        self.tab4 = QtGui.QWidget()
        self.tab4.setObjectName(_fromUtf8("tab4"))
        self.Section11 = QtGui.QGroupBox(self.tab4)
        self.Section11.setGeometry(QtCore.QRect(10, 160, 441, 151))
        self.Section11.setObjectName(_fromUtf8("Section11"))
        self.Megjegyzes = QtGui.QPlainTextEdit(self.Section11)
        self.Megjegyzes.setGeometry(QtCore.QRect(20, 20, 411, 121))
        self.Megjegyzes.setObjectName(_fromUtf8("Megjegyzes"))
        self.Section12 = QtGui.QGroupBox(self.tab4)
        self.Section12.setGeometry(QtCore.QRect(10, 320, 441, 221))
        self.Section12.setObjectName(_fromUtf8("Section12"))
        self.Calendar = QtGui.QCalendarWidget(self.Section12)
        self.Calendar.setGeometry(QtCore.QRect(90, 20, 251, 155))
        self.Calendar.setGridVisible(True)
        self.Calendar.setHorizontalHeaderFormat(QtGui.QCalendarWidget.ShortDayNames)
        self.Calendar.setVerticalHeaderFormat(QtGui.QCalendarWidget.NoVerticalHeader)
        self.Calendar.setNavigationBarVisible(True)
        self.Calendar.setDateEditEnabled(True)
        self.Calendar.setObjectName(_fromUtf8("Calendar"))
        self.Datum = QtGui.QLineEdit(self.Section12)
        self.Datum.setEnabled(True)
        self.Datum.setGeometry(QtCore.QRect(110, 180, 231, 23))
        self.Datum.setAlignment(QtCore.Qt.AlignCenter)
        self.Datum.setObjectName(_fromUtf8("Datum"))
        self.chckDatum = QtGui.QCheckBox(self.Section12)
        self.chckDatum.setGeometry(QtCore.QRect(90, 180, 16, 17))
        self.chckDatum.setText(_fromUtf8(""))
        self.chckDatum.setObjectName(_fromUtf8("chckDatum"))
        self.Section09 = QtGui.QGroupBox(self.tab4)
        self.Section09.setGeometry(QtCore.QRect(10, 10, 441, 51))
        self.Section09.setObjectName(_fromUtf8("Section09"))
        self.Muzeum = QtGui.QComboBox(self.Section09)
        self.Muzeum.setGeometry(QtCore.QRect(40, 20, 211, 22))
        self.Muzeum.setObjectName(_fromUtf8("Muzeum"))
        self.EgyebMuzeum = QtGui.QLineEdit(self.Section09)
        self.EgyebMuzeum.setGeometry(QtCore.QRect(260, 20, 171, 20))
        self.EgyebMuzeum.setObjectName(_fromUtf8("EgyebMuzeum"))
        self.chckMuzeum = QtGui.QCheckBox(self.Section09)
        self.chckMuzeum.setGeometry(QtCore.QRect(20, 20, 16, 17))
        self.chckMuzeum.setText(_fromUtf8(""))
        self.chckMuzeum.setObjectName(_fromUtf8("chckMuzeum"))
        self.Section10 = QtGui.QGroupBox(self.tab4)
        self.Section10.setGeometry(QtCore.QRect(10, 70, 441, 81))
        self.Section10.setObjectName(_fromUtf8("Section10"))
        self.BejelentoNev = QtGui.QLineEdit(self.Section10)
        self.BejelentoNev.setGeometry(QtCore.QRect(110, 20, 321, 20))
        self.BejelentoNev.setObjectName(_fromUtf8("BejelentoNev"))
        self.PersonName = QtGui.QLabel(self.Section10)
        self.PersonName.setGeometry(QtCore.QRect(20, 20, 46, 13))
        self.PersonName.setObjectName(_fromUtf8("PersonName"))
        self.WorkplaceName = QtGui.QLabel(self.Section10)
        self.WorkplaceName.setGeometry(QtCore.QRect(20, 50, 51, 16))
        self.WorkplaceName.setObjectName(_fromUtf8("WorkplaceName"))
        self.BejelentoMunkahely = QtGui.QLineEdit(self.Section10)
        self.BejelentoMunkahely.setGeometry(QtCore.QRect(110, 50, 321, 20))
        self.BejelentoMunkahely.setObjectName(_fromUtf8("BejelentoMunkahely"))
        self.chckBejelentoNev = QtGui.QCheckBox(self.Section10)
        self.chckBejelentoNev.setGeometry(QtCore.QRect(90, 20, 16, 17))
        self.chckBejelentoNev.setText(_fromUtf8(""))
        self.chckBejelentoNev.setObjectName(_fromUtf8("chckBejelentoNev"))
        self.chckBejelentoMunkahely = QtGui.QCheckBox(self.Section10)
        self.chckBejelentoMunkahely.setGeometry(QtCore.QRect(90, 50, 16, 17))
        self.chckBejelentoMunkahely.setText(_fromUtf8(""))
        self.chckBejelentoMunkahely.setObjectName(_fromUtf8("chckBejelentoMunkahely"))
        self.tabWidget.addTab(self.tab4, _fromUtf8(""))
        self.tab5 = QtGui.QWidget()
        self.tab5.setObjectName(_fromUtf8("tab5"))
        self.PDFMapScale = QtGui.QComboBox(self.tab5)
        self.PDFMapScale.setGeometry(QtCore.QRect(40, 80, 131, 22))
        self.PDFMapScale.setObjectName(_fromUtf8("PDFMapScale"))
        self.PDFMapOrientation = QtGui.QComboBox(self.tab5)
        self.PDFMapOrientation.setGeometry(QtCore.QRect(40, 30, 131, 22))
        self.PDFMapOrientation.setObjectName(_fromUtf8("PDFMapOrientation"))
        self.PDFMapOrientationName = QtGui.QLabel(self.tab5)
        self.PDFMapOrientationName.setGeometry(QtCore.QRect(20, 10, 81, 16))
        self.PDFMapOrientationName.setObjectName(_fromUtf8("PDFMapOrientationName"))
        self.PDFMapScaleName = QtGui.QLabel(self.tab5)
        self.PDFMapScaleName.setGeometry(QtCore.QRect(20, 60, 111, 16))
        self.PDFMapScaleName.setObjectName(_fromUtf8("PDFMapScaleName"))
        self.SavePDFButton = QtGui.QCommandLinkButton(self.tab5)
        self.SavePDFButton.setGeometry(QtCore.QRect(120, 310, 211, 50))
        self.SavePDFButton.setObjectName(_fromUtf8("SavePDFButton"))
        self.chckPDFMapOrientation = QtGui.QCheckBox(self.tab5)
        self.chckPDFMapOrientation.setGeometry(QtCore.QRect(20, 30, 16, 17))
        self.chckPDFMapOrientation.setText(_fromUtf8(""))
        self.chckPDFMapOrientation.setObjectName(_fromUtf8("chckPDFMapOrientation"))
        self.chckPDFMapScale = QtGui.QCheckBox(self.tab5)
        self.chckPDFMapScale.setGeometry(QtCore.QRect(20, 80, 16, 17))
        self.chckPDFMapScale.setText(_fromUtf8(""))
        self.chckPDFMapScale.setObjectName(_fromUtf8("chckPDFMapScale"))
        self.PDFMapPrint = QtGui.QCommandLinkButton(self.tab5)
        self.PDFMapPrint.setGeometry(QtCore.QRect(120, 400, 211, 50))
        self.PDFMapPrint.setObjectName(_fromUtf8("PDFMapPrint"))
        self.PDFMapTitleName = QtGui.QLabel(self.tab5)
        self.PDFMapTitleName.setGeometry(QtCore.QRect(20, 160, 71, 16))
        self.PDFMapTitleName.setObjectName(_fromUtf8("PDFMapTitleName"))
        self.PDFMapTitle = QtGui.QLineEdit(self.tab5)
        self.PDFMapTitle.setGeometry(QtCore.QRect(40, 180, 241, 20))
        self.PDFMapTitle.setObjectName(_fromUtf8("PDFMapTitle"))
        self.chckPDFMapTitle = QtGui.QCheckBox(self.tab5)
        self.chckPDFMapTitle.setGeometry(QtCore.QRect(20, 180, 16, 17))
        self.chckPDFMapTitle.setText(_fromUtf8(""))
        self.chckPDFMapTitle.setObjectName(_fromUtf8("chckPDFMapTitle"))
        self.PDFMapOrientationTip = QtGui.QLabel(self.tab5)
        self.PDFMapOrientationTip.setGeometry(QtCore.QRect(180, 30, 271, 16))
        self.PDFMapOrientationTip.setObjectName(_fromUtf8("PDFMapOrientationTip"))
        self.chckPDFMapResolution = QtGui.QCheckBox(self.tab5)
        self.chckPDFMapResolution.setGeometry(QtCore.QRect(20, 130, 16, 17))
        self.chckPDFMapResolution.setObjectName(_fromUtf8("chckPDFMapResolution"))
        self.PDFMapResolutionName = QtGui.QLabel(self.tab5)
        self.PDFMapResolutionName.setGeometry(QtCore.QRect(20, 110, 121, 16))
        self.PDFMapResolutionName.setObjectName(_fromUtf8("PDFMapResolutionName"))
        self.PDFMapResolution = QtGui.QComboBox(self.tab5)
        self.PDFMapResolution.setGeometry(QtCore.QRect(40, 130, 131, 22))
        self.PDFMapResolution.setObjectName(_fromUtf8("PDFMapResolution"))
        self.tabWidget.addTab(self.tab5, _fromUtf8(""))
        self.TitleName = QtGui.QLabel(LelohelyBejelento)
        self.TitleName.setGeometry(QtCore.QRect(0, 10, 491, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.TitleName.setFont(font)
        self.TitleName.setAlignment(QtCore.Qt.AlignCenter)
        self.TitleName.setObjectName(_fromUtf8("TitleName"))
        self.SaveToXMLButton = QtGui.QPushButton(LelohelyBejelento)
        self.SaveToXMLButton.setGeometry(QtCore.QRect(10, 630, 101, 23))
        self.SaveToXMLButton.setStyleSheet(_fromUtf8("font: italic 8pt \"MS Shell Dlg 2\";"))
        self.SaveToXMLButton.setObjectName(_fromUtf8("SaveToXMLButton"))
        self.LoadFromXMLButton = QtGui.QPushButton(LelohelyBejelento)
        self.LoadFromXMLButton.setGeometry(QtCore.QRect(120, 630, 111, 23))
        self.LoadFromXMLButton.setStyleSheet(_fromUtf8("font: italic 8pt \"MS Shell Dlg 2\";"))
        self.LoadFromXMLButton.setObjectName(_fromUtf8("LoadFromXMLButton"))
        self.VersionName = QtGui.QLabel(LelohelyBejelento)
        self.VersionName.setGeometry(QtCore.QRect(460, 10, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.VersionName.setFont(font)
        self.VersionName.setObjectName(_fromUtf8("VersionName"))
        self.Errors = QtGui.QPushButton(LelohelyBejelento)
        self.Errors.setGeometry(QtCore.QRect(240, 630, 51, 23))
        self.Errors.setStyleSheet(_fromUtf8("font: italic 8pt \"MS Shell Dlg 2\";"))
        self.Errors.setObjectName(_fromUtf8("Errors"))

        self.retranslateUi(LelohelyBejelento)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), LelohelyBejelento.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), LelohelyBejelento.reject)
        QtCore.QMetaObject.connectSlotsByName(LelohelyBejelento)
        LelohelyBejelento.setTabOrder(self.tabWidget, self.chckMegye)
        LelohelyBejelento.setTabOrder(self.chckMegye, self.Megye)
        LelohelyBejelento.setTabOrder(self.Megye, self.chckTelepules)
        LelohelyBejelento.setTabOrder(self.chckTelepules, self.Telepules)
        LelohelyBejelento.setTabOrder(self.Telepules, self.Utca)
        LelohelyBejelento.setTabOrder(self.Utca, self.Hazszam)
        LelohelyBejelento.setTabOrder(self.Hazszam, self.KOHAzon)
        LelohelyBejelento.setTabOrder(self.KOHAzon, self.LeloNev)
        LelohelyBejelento.setTabOrder(self.LeloNev, self.CRSAzon)
        LelohelyBejelento.setTabOrder(self.CRSAzon, self.EOVSzelveny)
        LelohelyBejelento.setTabOrder(self.EOVSzelveny, self.HRSZ)
        LelohelyBejelento.setTabOrder(self.HRSZ, self.FoldrLeiras)
        LelohelyBejelento.setTabOrder(self.FoldrLeiras, self.chckPontossag)
        LelohelyBejelento.setTabOrder(self.chckPontossag, self.Pontossag)
        LelohelyBejelento.setTabOrder(self.Pontossag, self.JellegCombo)
        LelohelyBejelento.setTabOrder(self.JellegCombo, self.PontosJelleg)
        LelohelyBejelento.setTabOrder(self.PontosJelleg, self.KorCombo)
        LelohelyBejelento.setTabOrder(self.KorCombo, self.PontosKor)
        LelohelyBejelento.setTabOrder(self.PontosKor, self.JellegKorTable)
        LelohelyBejelento.setTabOrder(self.JellegKorTable, self.AddJellegKorButton)
        LelohelyBejelento.setTabOrder(self.AddJellegKorButton, self.RemoveJellegKorButton)
        LelohelyBejelento.setTabOrder(self.RemoveJellegKorButton, self.LelohelyAllapot)
        LelohelyBejelento.setTabOrder(self.LelohelyAllapot, self.EgyebAllapot)
        LelohelyBejelento.setTabOrder(self.EgyebAllapot, self.LelohelyVeszely)
        LelohelyBejelento.setTabOrder(self.LelohelyVeszely, self.EgyebVeszely)
        LelohelyBejelento.setTabOrder(self.EgyebVeszely, self.ForrasTipusValue)
        LelohelyBejelento.setTabOrder(self.ForrasTipusValue, self.AddForrasButton)
        LelohelyBejelento.setTabOrder(self.AddForrasButton, self.RemoveForrasButton)
        LelohelyBejelento.setTabOrder(self.RemoveForrasButton, self.ForrasTable)
        LelohelyBejelento.setTabOrder(self.ForrasTable, self.AddTevekenysegButton)
        LelohelyBejelento.setTabOrder(self.AddTevekenysegButton, self.RemoveTevekenysegButton)
        LelohelyBejelento.setTabOrder(self.RemoveTevekenysegButton, self.TevekenysegTable)
        LelohelyBejelento.setTabOrder(self.TevekenysegTable, self.chckMuzeum)
        LelohelyBejelento.setTabOrder(self.chckMuzeum, self.Muzeum)
        LelohelyBejelento.setTabOrder(self.Muzeum, self.EgyebMuzeum)
        LelohelyBejelento.setTabOrder(self.EgyebMuzeum, self.chckBejelentoNev)
        LelohelyBejelento.setTabOrder(self.chckBejelentoNev, self.BejelentoNev)
        LelohelyBejelento.setTabOrder(self.BejelentoNev, self.chckBejelentoMunkahely)
        LelohelyBejelento.setTabOrder(self.chckBejelentoMunkahely, self.BejelentoMunkahely)
        LelohelyBejelento.setTabOrder(self.BejelentoMunkahely, self.Megjegyzes)
        LelohelyBejelento.setTabOrder(self.Megjegyzes, self.Calendar)
        LelohelyBejelento.setTabOrder(self.Calendar, self.chckDatum)
        LelohelyBejelento.setTabOrder(self.chckDatum, self.Datum)
        LelohelyBejelento.setTabOrder(self.Datum, self.SaveToXMLButton)
        LelohelyBejelento.setTabOrder(self.SaveToXMLButton, self.LoadFromXMLButton)
        LelohelyBejelento.setTabOrder(self.LoadFromXMLButton, self.buttonBox)

    def retranslateUi(self, LelohelyBejelento):
        LelohelyBejelento.setWindowTitle(QtGui.QApplication.translate("LelohelyBejelento", "Lelőhely-bejelentő készítő (LBK)", None, QtGui.QApplication.UnicodeUTF8))
        self.Section01.setTitle(QtGui.QApplication.translate("LelohelyBejelento", "A lelőhely megjelölése", None, QtGui.QApplication.UnicodeUTF8))
        self.CountyName.setText(QtGui.QApplication.translate("LelohelyBejelento", "Megye", None, QtGui.QApplication.UnicodeUTF8))
        self.CityName.setText(QtGui.QApplication.translate("LelohelyBejelento", "Város, település", None, QtGui.QApplication.UnicodeUTF8))
        self.HouseName.setText(QtGui.QApplication.translate("LelohelyBejelento", "Házszám", None, QtGui.QApplication.UnicodeUTF8))
        self.KOHName.setText(QtGui.QApplication.translate("LelohelyBejelento", "Nyilvántartási azonosító szám", None, QtGui.QApplication.UnicodeUTF8))
        self.RoadName.setText(QtGui.QApplication.translate("LelohelyBejelento", "Utca", None, QtGui.QApplication.UnicodeUTF8))
        self.Section02.setTitle(QtGui.QApplication.translate("LelohelyBejelento", "A lelőhely neve(i)", None, QtGui.QApplication.UnicodeUTF8))
        self.Section03.setTitle(QtGui.QApplication.translate("LelohelyBejelento", "A lelőhely pontos helye", None, QtGui.QApplication.UnicodeUTF8))
        self.CRSName.setText(QtGui.QApplication.translate("LelohelyBejelento", "A mellékelt térkép(vetület) fajtája", None, QtGui.QApplication.UnicodeUTF8))
        self.MapNumberName.setText(QtGui.QApplication.translate("LelohelyBejelento", "A térképlap száma", None, QtGui.QApplication.UnicodeUTF8))
        self.HRSZName.setText(QtGui.QApplication.translate("LelohelyBejelento", "Helyrajzi szám(ok)", None, QtGui.QApplication.UnicodeUTF8))
        self.GeoDescriptionName.setText(QtGui.QApplication.translate("LelohelyBejelento", "Földrajzi leírás", None, QtGui.QApplication.UnicodeUTF8))
        self.AccuracyName.setText(QtGui.QApplication.translate("LelohelyBejelento", "A helymeghatározás pontossága [m]", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), QtGui.QApplication.translate("LelohelyBejelento", "Általános adatok", None, QtGui.QApplication.UnicodeUTF8))
        self.Section04.setTitle(QtGui.QApplication.translate("LelohelyBejelento", "A lelőhelyen talált régészeti jelenségek adatai", None, QtGui.QApplication.UnicodeUTF8))
        self.AddJellegKorButton.setText(QtGui.QApplication.translate("LelohelyBejelento", "Sor hozzáadása", None, QtGui.QApplication.UnicodeUTF8))
        self.RemoveJellegKorButton.setText(QtGui.QApplication.translate("LelohelyBejelento", "Sor törlése", None, QtGui.QApplication.UnicodeUTF8))
        self.JellegKorTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("LelohelyBejelento", "Jelleg", None, QtGui.QApplication.UnicodeUTF8))
        self.JellegKorTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("LelohelyBejelento", "Kor", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), QtGui.QApplication.translate("LelohelyBejelento", "Régészeti jelenségek", None, QtGui.QApplication.UnicodeUTF8))
        self.Section05.setTitle(QtGui.QApplication.translate("LelohelyBejelento", "A lelőhely állapota", None, QtGui.QApplication.UnicodeUTF8))
        self.Section06.setTitle(QtGui.QApplication.translate("LelohelyBejelento", "A lelőhely veszélyeztetettsége", None, QtGui.QApplication.UnicodeUTF8))
        self.Section07.setTitle(QtGui.QApplication.translate("LelohelyBejelento", "A lelőhely ismertsége", None, QtGui.QApplication.UnicodeUTF8))
        self.ForrasTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("LelohelyBejelento", "Forrás típusa", None, QtGui.QApplication.UnicodeUTF8))
        self.ForrasTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("LelohelyBejelento", "Szerző", None, QtGui.QApplication.UnicodeUTF8))
        self.ForrasTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("LelohelyBejelento", "Cím", None, QtGui.QApplication.UnicodeUTF8))
        self.ForrasTable.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("LelohelyBejelento", "Jelzet", None, QtGui.QApplication.UnicodeUTF8))
        self.AddForrasButton.setText(QtGui.QApplication.translate("LelohelyBejelento", "Új sor hozzáadása", None, QtGui.QApplication.UnicodeUTF8))
        self.RemoveForrasButton.setText(QtGui.QApplication.translate("LelohelyBejelento", "Sor törlése", None, QtGui.QApplication.UnicodeUTF8))
        self.Section08.setTitle(QtGui.QApplication.translate("LelohelyBejelento", "A lelőhelyen végzett tevékenység", None, QtGui.QApplication.UnicodeUTF8))
        self.TevekenysegTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("LelohelyBejelento", "Év", None, QtGui.QApplication.UnicodeUTF8))
        self.TevekenysegTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("LelohelyBejelento", "Tevékenység", None, QtGui.QApplication.UnicodeUTF8))
        self.TevekenysegTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("LelohelyBejelento", "Név", None, QtGui.QApplication.UnicodeUTF8))
        self.TevekenysegTable.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("LelohelyBejelento", "Megjegyzés", None, QtGui.QApplication.UnicodeUTF8))
        self.AddTevekenysegButton.setText(QtGui.QApplication.translate("LelohelyBejelento", "Új sor hozzáadása", None, QtGui.QApplication.UnicodeUTF8))
        self.RemoveTevekenysegButton.setText(QtGui.QApplication.translate("LelohelyBejelento", "Sor törlése", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), QtGui.QApplication.translate("LelohelyBejelento", "További adatok", None, QtGui.QApplication.UnicodeUTF8))
        self.Section11.setTitle(QtGui.QApplication.translate("LelohelyBejelento", "Megjegyzés", None, QtGui.QApplication.UnicodeUTF8))
        self.Section12.setTitle(QtGui.QApplication.translate("LelohelyBejelento", "A bejelentés kelte", None, QtGui.QApplication.UnicodeUTF8))
        self.Section09.setTitle(QtGui.QApplication.translate("LelohelyBejelento", "A leleteket fogadó múzeum", None, QtGui.QApplication.UnicodeUTF8))
        self.Section10.setTitle(QtGui.QApplication.translate("LelohelyBejelento", "A bejelentő természetes személyazonosító adatai", None, QtGui.QApplication.UnicodeUTF8))
        self.PersonName.setText(QtGui.QApplication.translate("LelohelyBejelento", "Név", None, QtGui.QApplication.UnicodeUTF8))
        self.WorkplaceName.setText(QtGui.QApplication.translate("LelohelyBejelento", "Munkahely", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab4), QtGui.QApplication.translate("LelohelyBejelento", "Egyéb", None, QtGui.QApplication.UnicodeUTF8))
        self.PDFMapOrientationName.setText(QtGui.QApplication.translate("LelohelyBejelento", "Térkép tájolása", None, QtGui.QApplication.UnicodeUTF8))
        self.PDFMapScaleName.setText(QtGui.QApplication.translate("LelohelyBejelento", "Térkép méretaránya", None, QtGui.QApplication.UnicodeUTF8))
        self.SavePDFButton.setText(QtGui.QApplication.translate("LelohelyBejelento", "Szöveges lelőhely-bejelentő\n"
"mentése PDF-be", None, QtGui.QApplication.UnicodeUTF8))
        self.PDFMapPrint.setText(QtGui.QApplication.translate("LelohelyBejelento", "Lelőhely-bejelentő térkép\n"
"mentése PDF-be", None, QtGui.QApplication.UnicodeUTF8))
        self.PDFMapTitleName.setText(QtGui.QApplication.translate("LelohelyBejelento", "Térkép címe", None, QtGui.QApplication.UnicodeUTF8))
        self.PDFMapOrientationTip.setText(QtGui.QApplication.translate("LelohelyBejelento", "Javasolt: -", None, QtGui.QApplication.UnicodeUTF8))
        self.chckPDFMapResolution.setText(QtGui.QApplication.translate("LelohelyBejelento", "Kívánt felbontás", None, QtGui.QApplication.UnicodeUTF8))
        self.PDFMapResolutionName.setText(QtGui.QApplication.translate("LelohelyBejelento", "Kívánt felbontás (dpi)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab5), QtGui.QApplication.translate("LelohelyBejelento", "PDF mentés", None, QtGui.QApplication.UnicodeUTF8))
        self.TitleName.setText(QtGui.QApplication.translate("LelohelyBejelento", "LELŐHELY-BEJELENTŐ KÉSZÍTŐ", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveToXMLButton.setText(QtGui.QApplication.translate("LelohelyBejelento", "Mentés XML fájlba", None, QtGui.QApplication.UnicodeUTF8))
        self.LoadFromXMLButton.setText(QtGui.QApplication.translate("LelohelyBejelento", "Betöltés XML fájlból", None, QtGui.QApplication.UnicodeUTF8))
        self.VersionName.setText(QtGui.QApplication.translate("LelohelyBejelento", "v0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.Errors.setText(QtGui.QApplication.translate("LelohelyBejelento", "Hibák", None, QtGui.QApplication.UnicodeUTF8))

